# Generated by Django 4.0.4 on 2022-05-22 10:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_post_autor_post_data_post_imagem_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='prioridade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 11, 27, 4, 137594)),
        ),
    ]
