# Generated by Django 4.0.4 on 2022-05-23 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='post',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='post',
            name='prioridade',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 16, 46, 55, 882882)),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
