# Generated by Django 4.0.4 on 2022-05-23 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_post_concluido_remove_post_criado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link_linkedin', models.URLField(blank=True)),
                ('link_Lusofona', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 16, 52, 22, 600799)),
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('descricao', models.CharField(max_length=500)),
                ('cadeira', models.CharField(max_length=100)),
                ('ano_realizacao', models.IntegerField(default=0)),
                ('link_github', models.URLField(blank=True)),
                ('participantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
            ],
        ),
    ]
