# Generated by Django 4.0.4 on 2022-05-23 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_pessoa_alter_post_data_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 17, 23, 37, 854393)),
        ),
    ]
