# Generated by Django 4.0.4 on 2022-05-23 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_pessoa1_rename_link_lusofona_pessoa_link_lusofona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 17, 39, 44, 776207)),
        ),
    ]
