# Generated by Django 4.0.4 on 2022-05-23 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_post_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa1',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 17, 47, 10, 701056)),
        ),
    ]
