# Generated by Django 4.0.4 on 2022-05-23 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_delete_pessoa1_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 18, 57, 43, 251393)),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='cadeira',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='participantes',
        ),
        migrations.AddField(
            model_name='projetos',
            name='participantes',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
    ]
