# Generated by Django 4.0.4 on 2022-05-23 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_post_data_alter_projetos_cadeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 19, 15, 16, 136990)),
        ),
    ]
