# Generated by Django 4.0.4 on 2022-05-24 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cadeira', models.CharField(max_length=100)),
                ('ano_realizado', models.IntegerField(default=0)),
                ('ects', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('professores', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='projetos',
            name='gif',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='imagemGrande',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='linguagens',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projetos',
            name='projetoDownload',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 12, 51, 53, 746190)),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='cadeira',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('cadeiras', models.ManyToManyField(to='portfolio.cadeira')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projeto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio.Cadeira.projeto+', to='portfolio.projetos'),
        ),
    ]
