# Generated by Django 4.0.4 on 2022-05-24 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_cadeira_projetos_gif_projetos_imagemgrande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 14, 15, 10, 295260)),
        ),
    ]
