# Generated by Django 4.0.4 on 2022-05-25 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_cadeira_link_lusofona_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 10, 15, 37, 128416)),
        ),
    ]
