# Generated by Django 4.0.4 on 2022-05-25 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nome_escola', models.CharField(max_length=100)),
                ('link_escola', models.URLField(blank=True)),
                ('curso', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 6, 40, 357587)),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta4',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta5',
            field=models.CharField(max_length=50),
        ),
    ]
