# Generated by Django 4.0.4 on 2022-05-25 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 22, 26, 65532)),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('formacao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio.Certificado.formacao+', to='portfolio.formacao')),
            ],
        ),
    ]
