# Generated by Django 4.0.4 on 2022-05-25 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_post_data_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 30, 15, 250465)),
        ),
    ]
