# Generated by Django 4.0.4 on 2022-05-26 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_formacao_licenciatura_alter_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='licenciatura',
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='formacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.formacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 9, 52, 27, 406107)),
        ),
    ]
