# Generated by Django 4.0.4 on 2022-05-26 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_tecnologias_alter_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnologias',
            old_name='link_oficial',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 11, 51, 57, 417820)),
        ),
    ]
