# Generated by Django 4.0.4 on 2022-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cadeira', models.CharField(max_length=100)),
                ('ano_realizado', models.IntegerField(default=0)),
                ('ects', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('link_Lusofona', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nome_escola', models.CharField(max_length=100)),
                ('link_escola', models.URLField(blank=True)),
                ('curso', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link_linkedin', models.URLField(blank=True)),
                ('link_lusofona', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pergunta1', models.CharField(max_length=50)),
                ('pergunta2', models.CharField(max_length=50)),
                ('pergunta3', models.IntegerField(default=0)),
                ('pergunta4', models.IntegerField(default=0)),
                ('pergunta5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('acronimo', models.CharField(max_length=20)),
                ('ano_criacao', models.IntegerField(default=0)),
                ('criador', models.CharField(max_length=100)),
                ('logotipo', models.ImageField(null=True, upload_to='media/')),
                ('link', models.URLField(blank=True)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('imagemGrande', models.ImageField(null=True, upload_to='media/')),
                ('gif', models.ImageField(null=True, upload_to='media/')),
                ('descricao', models.CharField(max_length=500)),
                ('cadeira', models.CharField(max_length=100)),
                ('ano_realizacao', models.IntegerField(default=0)),
                ('link_github', models.URLField(blank=True)),
                ('linguagens', models.CharField(blank=True, max_length=100)),
                ('projetoDownload', models.FileField(blank=True, upload_to='')),
                ('participantes', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('cadeiras', models.ManyToManyField(to='portfolio.cadeira')),
                ('formacao', models.ManyToManyField(to='portfolio.formacao')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('formacao', models.ManyToManyField(to='portfolio.formacao')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projeto',
            field=models.ManyToManyField(related_name='portfolio.Cadeira.projeto+', to='portfolio.projetos'),
        ),
    ]
