# Generated by Django 4.0.4 on 2022-06-06 10:52

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_cadeira_projeto_cadeira_projeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path),
        ),
    ]
