# Generated by Django 4.0.4 on 2022-05-22 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_concluido_post_criado_post_prioridade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pergunta1', models.IntegerField(default=0)),
                ('pergunta2', models.IntegerField(default=0)),
                ('pergunta3', models.IntegerField(default=0)),
                ('pergunta4', models.CharField(max_length=50)),
                ('pergunta5', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 11, 30, 57, 585399)),
        ),
    ]
