# Generated by Django 4.0.4 on 2022-06-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='descricao',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
