# Generated by Django 4.0.4 on 2022-06-06 09:19

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path),
        ),
    ]
