# Generated by Django 4.0.4 on 2022-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='portfolio/media/'),
        ),
    ]
