# Generated by Django 4.0.4 on 2022-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.ImageField(null=True, upload_to='certificado/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticia/'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='gif',
            field=models.ImageField(null=True, upload_to='projeto/'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='projeto/'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='imagemGrande',
            field=models.ImageField(null=True, upload_to='projeto/'),
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='logotipo',
            field=models.ImageField(null=True, upload_to='tecnologia/'),
        ),
    ]
