# Generated by Django 4.0.4 on 2022-06-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_quizz_imagem_alter_certificado_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='imagem',
        ),
    ]
