# Generated by Django 4.0.4 on 2022-05-23 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link_linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='link_Lusofona',
            new_name='link_lusofona',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 17, 38, 49, 997079)),
        ),
    ]
