# Generated by Django 4.0.4 on 2022-05-25 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='link_Lusofona',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 10, 7, 10, 726438)),
        ),
    ]
