# Generated by Django 4.0.4 on 2022-05-25 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_formacao_alter_post_data_alter_quizz_pergunta1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 12, 28, 580953)),
        ),
    ]
