# Generated by Django 4.0.4 on 2022-05-25 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 31, 42, 12972)),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta4',
            field=models.IntegerField(default=0),
        ),
    ]
