# Generated by Django 4.0.4 on 2022-05-26 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_post_data_alter_quizz_pergunta4'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacao',
            name='licenciatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.licenciatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 9, 51, 13, 554201)),
        ),
    ]
