# Generated by Django 4.0.4 on 2022-05-26 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_remove_formacao_licenciatura_licenciatura_formacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 10, 37, 56, 444748)),
        ),
    ]
