# Generated by Django 4.0.4 on 2022-05-27 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_rename_link_oficial_tecnologias_link_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 18, 55, 989998)),
        ),
    ]
